-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2019-10-03 14:40:04.674

-- tables
-- Table: SP_DLCLASSES
ALTER TABLE STUDENT_UNAVAILABILITY DROP FOREIGN KEY fk1;
ALTER TABLE DLCLASSES DROP FOREIGN KEY fk2;
ALTER TABLE LEAVE_REQUEST DROP FOREIGN KEY fk3;
ALTER TABLE STUDENT_UNAVAILABILITY DROP FOREIGN KEY fk4;
ALTER TABLE STUDENT_UNAVAILABILITY DROP FOREIGN KEY fk5;
ALTER TABLE DLCLASSES DROP FOREIGN KEY fk6;
ALTER TABLE DLCLASSES DROP FOREIGN KEY fk7;
ALTER TABLE LEAVE_REQUEST DROP FOREIGN KEY fk8;


DROP TABLE IF EXISTS DLCLASSES, LEAVE_REQUEST, STUDENT_UNAVAILABILITY, USER, TIME;

CREATE TABLE DLCLASSES (
    DL_CLASS_ID int NOT NULL AUTO_INCREMENT,
    DL_COURSE_ID varchar(10) NOT NULL,
	DL_START_TIME int  NOT NULL,
    DL_END_TIME int NOT NULL,
    DL_CLASS_LOCATION varchar(15) NOT NULL,
    DL_CLASS_DAY varchar(10) NOT NULL,
    ASSIGNED_USER_ID int NULL ,
    IS_ASSIGNED boolean NOT NULL DEFAULT 0,
    CONSTRAINT DLCLASSES_pk PRIMARY KEY (DL_CLASS_ID)
);

-- Table: SP_LEAVE_REQUEST
CREATE TABLE LEAVE_REQUEST (
    LR_ID int NOT NULL AUTO_INCREMENT,
    LR_USER_ID int NOT NULL,
    LR_CLASS_TO_COVER int NOT NULL,
    LR_DATE date NOT NULL,
    LR_IS_ACCEPTED boolean NULL DEFAULT 0,
	LR_IS_REJECTED boolean NULL DEFAULT 0,
    CONSTRAINT LEAVE_REQUEST_pk PRIMARY KEY (LR_ID)
);

-- Table: SP_STUDENT_UNAVAILABILITY
CREATE TABLE STUDENT_UNAVAILABILITY (
    STD_UNAVAILABILITY_ID int NOT NULL AUTO_INCREMENT,
    STD_USER_ID int NULL,
    STD_IS_CLASS boolean Not NULL,
    STD_COURSEID varchar(10) NULL,
    STD_START_TIME int NOT NULL,
    STD_END_TIME int NOT NULL,
    STD_CLASS_LOCATION varchar(15) NULL,
    STD_DAY varchar(10) NOT NULL, 
    IS_DL boolean Not NULL,
    CONSTRAINT STUDENT_UNAVAILABILITY_pk PRIMARY KEY (STD_UNAVAILABILITY_ID)

);

-- Table: SP_USER
CREATE TABLE USER (
    USER_ID int NOT NULL,
    FIRST_NAME varchar(20) NOT NULL,
    LAST_NAME varchar(20) NOT NULL,
    EMAIL varchar(25) NOT NULL,
	PASSWORD varchar(60) NOT NULL,
    PREFERRED_HRS int NOT NULL DEFAULT 20,
    IS_ADMIN BOOLEAN NOT NULL DEFAULT 0,
    START_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT USER_pk PRIMARY KEY (USER_ID)
);

-- Table: TIME
CREATE TABLE TIME (
    ID int NOT NULL AUTO_INCREMENT,
    TIME_VAL VARCHAR(10) NOT NULL,

    CONSTRAINT TIME_pk PRIMARY KEY (ID)
);

-- foreign keys
-- Reference: fk1 (table: SP_STUDENT_UNAVAILABILITY)
ALTER TABLE STUDENT_UNAVAILABILITY ADD CONSTRAINT fk1 FOREIGN KEY fk1 (STD_USER_ID)
    REFERENCES USER (USER_ID);

-- Reference: fk2 (table: SP_DLCLASSES)
ALTER TABLE DLCLASSES ADD CONSTRAINT fk2 FOREIGN KEY fk2 (ASSIGNED_USER_ID)
    REFERENCES USER (USER_ID);

-- Reference: fk3 (table: SP_LEAVE_REQUEST)
ALTER TABLE LEAVE_REQUEST ADD CONSTRAINT fk3 FOREIGN KEY fk3 (LR_USER_ID)
    REFERENCES USER (USER_ID);

-- Reference: fk4 (table: SP_STUDENT_UNAVAILABILITY)
ALTER TABLE STUDENT_UNAVAILABILITY ADD CONSTRAINT fk4 FOREIGN KEY fk4 (STD_START_TIME)
    REFERENCES TIME (ID);

-- Reference: fk5 (table: SP_STUDENT_UNAVAILABILITY)
ALTER TABLE STUDENT_UNAVAILABILITY ADD CONSTRAINT fk5 FOREIGN KEY fk5 (STD_END_TIME)
    REFERENCES TIME (ID);
    
-- Reference: fk6 (table: SP_DLCLASSES)
ALTER TABLE DLCLASSES ADD CONSTRAINT fk6 FOREIGN KEY fk6 (DL_START_TIME)
    REFERENCES TIME (ID);

-- Reference: fk6 (table: SP_DLCLASSES)
ALTER TABLE DLCLASSES ADD CONSTRAINT fk7 FOREIGN KEY fk7 (DL_END_TIME)
    REFERENCES TIME (ID);
    
-- Reference: fk3 (table: SP_LEAVE_REQUEST)
ALTER TABLE LEAVE_REQUEST ADD CONSTRAINT fk8 FOREIGN KEY fk8 (LR_CLASS_TO_COVER)
    REFERENCES DLCLASSES (DL_CLASS_ID);
    
-- End of file.

