-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2019-10-03 14:40:04.674

-- tables
-- Table: SP_DLCLASSES

DROP TABLE IF EXISTS SP_DLCLASSES, SP_LEAVE_REQUEST, SP_STUDENT_UNAVAILABILITY, SP_USER;

CREATE TABLE SP_DLCLASSES (
    DL_CLASS_ID int NOT NULL AUTO_INCREMENT,
    DL_COURSE_ID varchar(10) NULL,
    DL_START_TIME time NULL,
    DL_END_TIME time NULL,
    DL_CLASS_LOCATION varchar(15) NULL,
    ASSIGNED_USER_ID int NULL,
    IS_ASSIGNED boolean NULL,
    CONSTRAINT SP_DLCLASSES_pk PRIMARY KEY (DL_CLASS_ID)
);

-- Table: SP_LEAVE_REQUEST
CREATE TABLE SP_LEAVE_REQUEST (
    LR_ID int NOT NULL AUTO_INCREMENT,
    LR_USER_ID int NOT NULL,
    LR_START_TIME time NULL,
    LR_END_TIME time NULL,
    LR_DATE date NULL,
    LR_IS_ACCEPTED boolean NULL,
    CONSTRAINT SP_LEAVE_REQUEST_pk PRIMARY KEY (LR_ID)
);

-- Table: SP_STUDENT_UNAVAILABILITY
CREATE TABLE SP_STUDENT_UNAVAILABILITY (
    STD_UNAVAILABILITY_ID int NOT NULL AUTO_INCREMENT,
    STD_USER_ID int NOT NULL,
    STD_IS_CLASS boolean NULL,
    STD_COURSEID varchar(10) NULL,
    STD_START_TIME time NULL,
    STD_END_TIME time NULL,
    STD_CLASS_LOCATION varchar(15) NULL,
    CONSTRAINT SP_STUDENT_UNAVAILABILITY_pk PRIMARY KEY (STD_UNAVAILABILITY_ID)
);

-- Table: SP_USER
CREATE TABLE SP_USER (
    USER_ID int NOT NULL,
    USER_NAME varchar(10) NOT NULL,
    USER_EMAIL varchar(50) NOT NULL,
    PASSWORD varchar(50) NOT NULL,
    CONSTRAINT SP_USER_pk PRIMARY KEY (USER_ID)
);

-- foreign keys
-- Reference: fk1 (table: SP_STUDENT_UNAVAILABILITY)
ALTER TABLE SP_STUDENT_UNAVAILABILITY ADD CONSTRAINT fk1 FOREIGN KEY fk1 (STD_USER_ID)
    REFERENCES SP_USER (USER_ID);

-- Reference: fk2 (table: SP_DLCLASSES)
ALTER TABLE SP_DLCLASSES ADD CONSTRAINT fk2 FOREIGN KEY fk2 (ASSIGNED_USER_ID)
    REFERENCES SP_USER (USER_ID);

-- Reference: fk3 (table: SP_LEAVE_REQUEST)
ALTER TABLE SP_LEAVE_REQUEST ADD CONSTRAINT fk3 FOREIGN KEY fk3 (LR_USER_ID)
    REFERENCES SP_USER (USER_ID);

-- End of file.

